spring:
  jpa:
    hibernate:
      lazy: false
    open-in-view: true
server:
  port: 8133
zookeeper: ${ZOOKEEPER_URL:localhost:2181}

ranger:
  server: ${RANGER_SERVER:172.16.2.217}        #空网关注册的服务地址   (注意需注入k8s地址，否则找不到服务)
  kong:
    server: ${KONG_SERVER:http://testkong.aceg.com}   #空网关地址
    name: ${KONG_NAME:ranger-clubadmin}     #空网关注册服务名称（项目名）
    enable: ${KONG_ENABLE:true}
    cors: ${KONG_CORS:http://testcms.acegear.com}     #容许跨域地址   目前为*
    host: ${KONG_HOST:testclub.acegear.com}   # 容许访问的host
    web: ${KONG_WEB:test-clubadmin.acegear.com}       # 容许访问的host（web域名）
    web2: ${KONG_WEB2:demo.club.acegear.com}       # 容许访问的host（web域名）



redis:
  url: ${REDIS_HOST:r-2ze5tzi6ontgfvs6igpd.redis.rds.aliyuncs.com}
  auth: ${REDIS_AUTH:5Mg5EhMvKg9Knv9Gnm0d}
qiniu:
  accessKey: hAr7ttsrGWq-GL5qRea6ApmvIuLmbmu2jkj09fSW
  secretKey: uaY-42qUeEFpaLAiotjB9VgYn6X65cqAsvxCQsVi
  bucket:
    img: acegear-img
  bucketUrl:
    img: https://img.acegear.com/
horizon:
  api: ${HORIZON_API:https://api2.acegear.cn/}

---



